### PR TITLE
rollback device's model as `TCL M3G`, update radio version from 1.5 to 1.7

### PR DESCRIPTION
**Pull request by imknown**
rollback device's PRODUCT_MODEL as `TCL M3G`, and update radio version from 1.5 to 1.7, fetched from TCL M3G Offical LEWA ROM: `LeWa_TCL_M3G_ROM_15.08.21.15.zip` http://bbs.tclmobile.com.cn/thread-27868-1-1.html

### CODE REVIEW

**Comment by AlvaroBrey** [comment]
The radio files seem fine.
PRODUCT_MODEL should be only the model, not including the brand. Otherwise apps such as Google Play will show the phone as "TCL TCL M3G". Some examples: 
https://github.com/armani-dev/android_device_xiaomi_armani/blob/cm-13.0/cm.mk#L31
https://github.com/dhacker29/android_device_motorola_falcon/blob/caf/full_falcon.mk#L35
https://github.com/CyanogenMod/android_device_oneplus_bacon/blob/cm-12.1/cm.mk#L30

IF you had made this into two separate commits I could cherrypick the radio one or merge both and then revert the PRODUCT MODEL. Keep in mind that in Git separate changes are meant to go in separate commits.

**Comment by imknown** [comment]
en.. perhaps i changed the wrong file cm.mk instead of the one i want (iam sorry and i've no on developing rom programming). i flashed your latest R3 rom and found the model in 'about phone' is M3G, but the phone's origin model is TCL M3G when i bought this tcl phone.

thank you, and i'll split my commit, ohhh, right, iam a noob, haha.

**Comment by AlvaroBrey** [comment]
The fact that in stock TCL says that doesn't mean it is right. You changed the right file but the change is not correct. Model is just the model name, without the brand.

**Comment by imknown** [comment]
en, i checked and  u r right. just because the data of websites has recorded it as `TCL M3G`. if i use `M3G`, most of them show that i am using one modified Android Device. :frowning:

**Pull request closed without merging**
